# TensorFlow 2.0 Complete Course - Python Neural Networks for Beginners

## Learning outline

* Image Classification
* Data Clustering
* Regression
* Reinforcement Learning
* Natural Language Processing

## How TensorFlows actually work?

TensorFlow has two main components that we will try to understand.

* Graphs
* Sessions

TensorFlow work by building a graph of defined computations. Nothing is computed or stored in this graph. It is simply a way for defining the operations that have been written in code.

A TensorFlow sessions allows parts of the graph to be executed. It allocates memory and resources and handles the execution of the operations and computations we've defined.

In some instances we will need to run a session to be able to execute parts of the graph we've created earlier.

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/opt/homebrew/Caskroom/miniconda/base/envs/tensorflow/lib/python3.10/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors

"A tesor is generalization of vectors and matrices to potentially higher dimensions. Internall, TensorFlow represents tensors as n-dimensional arrays of bease datatypes."

It should't surprise you that tensors are a fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout the program. Each tensor represents a patialy defined computation that will evntually produce a value. TensorFlow programs work by building a graph of Thensor objects that details how tensors are realated. Running different of the graph allow results to be generated.

Each tensor has data type and a shap.

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

## Creating Tensors
Below is an exmaple of how to create some differnt tensors.

In [7]:
# tf.Variable(Value, datatype)
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
# Now these tensor are sclar because they have only one value

## Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involed in the tensor. What we created above is a tensor of rank 0, also know as scalar.

Now we'll create some tensors of higher degrees/ranks.

In [8]:
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok", "Tim"], ["Test", "Ok", "Tim"]], tf.string)

**To determine the rank** of tensor we can call the followwing method.

In [11]:
rank_2 = tf.rank(rank2_tensor)
rank_1 = tf.rank(rank1_tensor)
rank_0 = tf.rank(string)

rank_2, rank_1, rank_0

# <tf.Tensor: shape=(), dtype=int32, numpy=2> --> numpy=2 means rank 2 tensor
# <tf.Tensor: shape=(), dtype=int32, numpy=1> --> numpy=1 means rank 1 tensor
# <tf.Tensor: shape=(), dtype=int32, numpy=0> --> numpy=0 means this data is a scalar

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

## Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of tensor is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shpae of tensor but sometimes it may be unknow.

To **get the shape** of a tensor we use the shape attribute.

In [14]:
# .shpae use for find the number of the elemnet in the tensor --> (row, columm) ** for 2D or above **

rank_2_shape = rank2_tensor.shape
rank_1_shape = rank1_tensor.shape
rank_0_shape = string.shape

rank_2_shape, rank_1_shape, rank_0_shape

(TensorShape([2, 3]), TensorShape([3]), TensorShape([]))

## Changing Shape 
The number of elements of a tensor is the product of the sizes of all shpaes. Ther are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor.

The example below shows how to change the shpae of a tensor.

In [16]:
tensor1 = tf.ones([1,2,3]); print(tensor1)              # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]); print(tensor2)  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]); print(tensor3)   # -1 tells the tensor to calculate the size of the dimension in that place
                                                        # This will reshape the tensor to [3,2]

# IMPORTANT : The number of elements in the reshaped tensor MUST match the number in the original

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors
Before we go to far i will mention that there are different types of tensors. These are the most commonly used and we will talk more in depth about each as they are used.

* Vaiable
* Constant
* Placeholder
* SparseTensor

With the execption of Variable all of these tensors are immuttable, meaning their value may not change during execution.

For now it is sufficient to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

## Evaluating Tensors

There will be some times throughout this guide we need to evaluate a tensor. In other words, get it's value. Since tensors repersent a partially complete compuatation we will sometimes need to run what's called a session to evaluate the tensor.

There are many different ways to achieve this but i will note the simplest way below.

In [ ]:
with tf.Session() as sess :
    tf.Tensor.eval()

# Now it's not working

Example

In [30]:
example_tensor = tf.zeros([5,5,5,5])
example_tensor = tf.reshape(example_tensor, [25,-1])
example_tensor

<tf.Tensor: shape=(25, 25), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0.